// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: messages.proto

package messages

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Event_EventType int32

const (
	INPUT     Event_EventType = 0
	OUTPUT    Event_EventType = 1
	SCENE     Event_EventType = 2
	TAMPERING Event_EventType = 3
)

var Event_EventType_name = map[int32]string{
	0: "INPUT",
	1: "OUTPUT",
	2: "SCENE",
	3: "TAMPERING",
}

var Event_EventType_value = map[string]int32{
	"INPUT":     0,
	"OUTPUT":    1,
	"SCENE":     2,
	"TAMPERING": 3,
}

func (Event_EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0, 0}
}

type Event struct {
	Type  Event_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=messages.Event_EventType" json:"type,omitempty"`
	Value int64           `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	ID    int32           `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (m *Event) Reset()      { *m = Event{} }
func (*Event) ProtoMessage() {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Event.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return m.Size()
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() Event_EventType {
	if m != nil {
		return m.Type
	}
	return INPUT
}

func (m *Event) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Event) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type Snapshot struct {
	Inputs        int64           `protobuf:"varint,1,opt,name=Inputs,proto3" json:"Inputs,omitempty"`
	Outputs       int64           `protobuf:"varint,2,opt,name=Outputs,proto3" json:"Outputs,omitempty"`
	RawInputs     int64           `protobuf:"varint,3,opt,name=RawInputs,proto3" json:"RawInputs,omitempty"`
	RawOutputs    int64           `protobuf:"varint,4,opt,name=RawOutputs,proto3" json:"RawOutputs,omitempty"`
	AllInputs     int64           `protobuf:"varint,5,opt,name=AllInputs,proto3" json:"AllInputs,omitempty"`
	AllOutputs    int64           `protobuf:"varint,6,opt,name=AllOutputs,proto3" json:"AllOutputs,omitempty"`
	InputsMap     map[int32]int64 `protobuf:"bytes,11,rep,name=inputsMap,proto3" json:"inputsMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	OutputsMap    map[int32]int64 `protobuf:"bytes,12,rep,name=outputsMap,proto3" json:"outputsMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	RawInputsMap  map[int32]int64 `protobuf:"bytes,13,rep,name=rawInputsMap,proto3" json:"rawInputsMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	RawOutputsMap map[int32]int64 `protobuf:"bytes,14,rep,name=rawOutputsMap,proto3" json:"rawOutputsMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	AllInputsMap  map[int32]int64 `protobuf:"bytes,15,rep,name=allInputsMap,proto3" json:"allInputsMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	AllOutputsMap map[int32]int64 `protobuf:"bytes,16,rep,name=allOutputsMap,proto3" json:"allOutputsMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	TamperingMap  map[int32]int64 `protobuf:"bytes,17,rep,name=tamperingMap,proto3" json:"tamperingMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (m *Snapshot) Reset()      { *m = Snapshot{} }
func (*Snapshot) ProtoMessage() {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}
func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return m.Size()
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetInputs() int64 {
	if m != nil {
		return m.Inputs
	}
	return 0
}

func (m *Snapshot) GetOutputs() int64 {
	if m != nil {
		return m.Outputs
	}
	return 0
}

func (m *Snapshot) GetRawInputs() int64 {
	if m != nil {
		return m.RawInputs
	}
	return 0
}

func (m *Snapshot) GetRawOutputs() int64 {
	if m != nil {
		return m.RawOutputs
	}
	return 0
}

func (m *Snapshot) GetAllInputs() int64 {
	if m != nil {
		return m.AllInputs
	}
	return 0
}

func (m *Snapshot) GetAllOutputs() int64 {
	if m != nil {
		return m.AllOutputs
	}
	return 0
}

func (m *Snapshot) GetInputsMap() map[int32]int64 {
	if m != nil {
		return m.InputsMap
	}
	return nil
}

func (m *Snapshot) GetOutputsMap() map[int32]int64 {
	if m != nil {
		return m.OutputsMap
	}
	return nil
}

func (m *Snapshot) GetRawInputsMap() map[int32]int64 {
	if m != nil {
		return m.RawInputsMap
	}
	return nil
}

func (m *Snapshot) GetRawOutputsMap() map[int32]int64 {
	if m != nil {
		return m.RawOutputsMap
	}
	return nil
}

func (m *Snapshot) GetAllInputsMap() map[int32]int64 {
	if m != nil {
		return m.AllInputsMap
	}
	return nil
}

func (m *Snapshot) GetAllOutputsMap() map[int32]int64 {
	if m != nil {
		return m.AllOutputsMap
	}
	return nil
}

func (m *Snapshot) GetTamperingMap() map[int32]int64 {
	if m != nil {
		return m.TamperingMap
	}
	return nil
}

type CountingActor struct {
	Address string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	ID      string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (m *CountingActor) Reset()      { *m = CountingActor{} }
func (*CountingActor) ProtoMessage() {}
func (*CountingActor) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}
func (m *CountingActor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CountingActor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CountingActor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CountingActor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountingActor.Merge(m, src)
}
func (m *CountingActor) XXX_Size() int {
	return m.Size()
}
func (m *CountingActor) XXX_DiscardUnknown() {
	xxx_messageInfo_CountingActor.DiscardUnknown(m)
}

var xxx_messageInfo_CountingActor proto.InternalMessageInfo

func (m *CountingActor) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CountingActor) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type CameraConfig struct {
	Url      string `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	Hostname string `protobuf:"bytes,2,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	Port     string `protobuf:"bytes,3,opt,name=Port,proto3" json:"Port,omitempty"`
	IP       string `protobuf:"bytes,4,opt,name=IP,proto3" json:"IP,omitempty"`
}

func (m *CameraConfig) Reset()      { *m = CameraConfig{} }
func (*CameraConfig) ProtoMessage() {}
func (*CameraConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}
func (m *CameraConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CameraConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CameraConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CameraConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CameraConfig.Merge(m, src)
}
func (m *CameraConfig) XXX_Size() int {
	return m.Size()
}
func (m *CameraConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CameraConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CameraConfig proto.InternalMessageInfo

func (m *CameraConfig) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CameraConfig) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *CameraConfig) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *CameraConfig) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

//Service interface
type Start struct {
}

func (m *Start) Reset()      { *m = Start{} }
func (*Start) ProtoMessage() {}
func (*Start) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}
func (m *Start) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Start) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Start.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Start) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Start.Merge(m, src)
}
func (m *Start) XXX_Size() int {
	return m.Size()
}
func (m *Start) XXX_DiscardUnknown() {
	xxx_messageInfo_Start.DiscardUnknown(m)
}

var xxx_messageInfo_Start proto.InternalMessageInfo

type Stop struct {
}

func (m *Stop) Reset()      { *m = Stop{} }
func (*Stop) ProtoMessage() {}
func (*Stop) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}
func (m *Stop) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Stop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Stop.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Stop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stop.Merge(m, src)
}
func (m *Stop) XXX_Size() int {
	return m.Size()
}
func (m *Stop) XXX_DiscardUnknown() {
	xxx_messageInfo_Stop.DiscardUnknown(m)
}

var xxx_messageInfo_Stop proto.InternalMessageInfo

type Restart struct {
}

func (m *Restart) Reset()      { *m = Restart{} }
func (*Restart) ProtoMessage() {}
func (*Restart) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{6}
}
func (m *Restart) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Restart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Restart.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Restart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restart.Merge(m, src)
}
func (m *Restart) XXX_Size() int {
	return m.Size()
}
func (m *Restart) XXX_DiscardUnknown() {
	xxx_messageInfo_Restart.DiscardUnknown(m)
}

var xxx_messageInfo_Restart proto.InternalMessageInfo

type StatusRequest struct {
}

func (m *StatusRequest) Reset()      { *m = StatusRequest{} }
func (*StatusRequest) ProtoMessage() {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{7}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusResponse struct {
	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *StatusResponse) Reset()      { *m = StatusResponse{} }
func (*StatusResponse) ProtoMessage() {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{8}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type InfoCounterRequest struct {
}

func (m *InfoCounterRequest) Reset()      { *m = InfoCounterRequest{} }
func (*InfoCounterRequest) ProtoMessage() {}
func (*InfoCounterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{9}
}
func (m *InfoCounterRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InfoCounterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InfoCounterRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InfoCounterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoCounterRequest.Merge(m, src)
}
func (m *InfoCounterRequest) XXX_Size() int {
	return m.Size()
}
func (m *InfoCounterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoCounterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoCounterRequest proto.InternalMessageInfo

type InfoCounterResponse struct {
	Inputs  int64 `protobuf:"varint,1,opt,name=Inputs,proto3" json:"Inputs,omitempty"`
	Outputs int64 `protobuf:"varint,2,opt,name=Outputs,proto3" json:"Outputs,omitempty"`
}

func (m *InfoCounterResponse) Reset()      { *m = InfoCounterResponse{} }
func (*InfoCounterResponse) ProtoMessage() {}
func (*InfoCounterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{10}
}
func (m *InfoCounterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InfoCounterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InfoCounterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InfoCounterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoCounterResponse.Merge(m, src)
}
func (m *InfoCounterResponse) XXX_Size() int {
	return m.Size()
}
func (m *InfoCounterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoCounterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoCounterResponse proto.InternalMessageInfo

func (m *InfoCounterResponse) GetInputs() int64 {
	if m != nil {
		return m.Inputs
	}
	return 0
}

func (m *InfoCounterResponse) GetOutputs() int64 {
	if m != nil {
		return m.Outputs
	}
	return 0
}

func init() {
	proto.RegisterEnum("messages.Event_EventType", Event_EventType_name, Event_EventType_value)
	proto.RegisterType((*Event)(nil), "messages.Event")
	proto.RegisterType((*Snapshot)(nil), "messages.Snapshot")
	proto.RegisterMapType((map[int32]int64)(nil), "messages.Snapshot.AllInputsMapEntry")
	proto.RegisterMapType((map[int32]int64)(nil), "messages.Snapshot.AllOutputsMapEntry")
	proto.RegisterMapType((map[int32]int64)(nil), "messages.Snapshot.InputsMapEntry")
	proto.RegisterMapType((map[int32]int64)(nil), "messages.Snapshot.OutputsMapEntry")
	proto.RegisterMapType((map[int32]int64)(nil), "messages.Snapshot.RawInputsMapEntry")
	proto.RegisterMapType((map[int32]int64)(nil), "messages.Snapshot.RawOutputsMapEntry")
	proto.RegisterMapType((map[int32]int64)(nil), "messages.Snapshot.TamperingMapEntry")
	proto.RegisterType((*CountingActor)(nil), "messages.CountingActor")
	proto.RegisterType((*CameraConfig)(nil), "messages.CameraConfig")
	proto.RegisterType((*Start)(nil), "messages.Start")
	proto.RegisterType((*Stop)(nil), "messages.Stop")
	proto.RegisterType((*Restart)(nil), "messages.Restart")
	proto.RegisterType((*StatusRequest)(nil), "messages.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "messages.StatusResponse")
	proto.RegisterType((*InfoCounterRequest)(nil), "messages.InfoCounterRequest")
	proto.RegisterType((*InfoCounterResponse)(nil), "messages.InfoCounterResponse")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 690 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xcf, 0x6f, 0x12, 0x41,
	0x14, 0xc7, 0x19, 0x60, 0x29, 0xfb, 0x5a, 0x28, 0x1d, 0x1b, 0x83, 0x8d, 0x99, 0xe0, 0x46, 0x0d,
	0x17, 0x7b, 0xa8, 0x1e, 0xd4, 0xd4, 0xd4, 0x2d, 0x25, 0xed, 0xc6, 0xb4, 0x25, 0x03, 0xbd, 0x3b,
	0xda, 0x29, 0x12, 0x61, 0x77, 0xdd, 0x1d, 0xda, 0x70, 0xf3, 0x4f, 0xf0, 0xec, 0x5f, 0xe0, 0x9f,
	0xe2, 0xb1, 0xc7, 0x1e, 0xed, 0xf6, 0xe2, 0xb1, 0x57, 0x6f, 0x66, 0x66, 0x7f, 0xb0, 0x14, 0x7a,
	0xd8, 0x0b, 0x99, 0xf7, 0xe6, 0x7d, 0xbe, 0xf3, 0x9d, 0x79, 0xf0, 0x80, 0xea, 0x88, 0xfb, 0x3e,
	0xeb, 0x73, 0x7f, 0xd3, 0xf5, 0x1c, 0xe1, 0xe0, 0x72, 0x1c, 0x1b, 0x3f, 0x11, 0x68, 0xed, 0x73,
	0x6e, 0x0b, 0xfc, 0x02, 0x8a, 0x62, 0xe2, 0xf2, 0x3a, 0x6a, 0xa0, 0x66, 0x75, 0xeb, 0xd1, 0x66,
	0x82, 0xa8, 0xed, 0xf0, 0xb3, 0x37, 0x71, 0x39, 0x55, 0x65, 0x78, 0x1d, 0xb4, 0x73, 0x36, 0x1c,
	0xf3, 0x7a, 0xbe, 0x81, 0x9a, 0x05, 0x1a, 0x06, 0xb8, 0x0a, 0x79, 0x6b, 0xaf, 0x5e, 0x68, 0xa0,
	0xa6, 0x46, 0xf3, 0xd6, 0x9e, 0xb1, 0x0d, 0x7a, 0x02, 0x62, 0x1d, 0x34, 0xeb, 0xa8, 0x73, 0xd2,
	0xab, 0xe5, 0x30, 0x40, 0xe9, 0xf8, 0xa4, 0x27, 0xd7, 0x48, 0xa6, 0xbb, 0xad, 0xf6, 0x51, 0xbb,
	0x96, 0xc7, 0x15, 0xd0, 0x7b, 0xe6, 0x61, 0xa7, 0x4d, 0xad, 0xa3, 0xfd, 0x5a, 0xc1, 0xf8, 0x57,
	0x86, 0x72, 0xd7, 0x66, 0xae, 0xff, 0xc5, 0x11, 0xf8, 0x21, 0x94, 0x2c, 0xdb, 0x1d, 0x0b, 0x5f,
	0x39, 0x2c, 0xd0, 0x28, 0xc2, 0x75, 0x58, 0x3a, 0x1e, 0x0b, 0xb5, 0x11, 0x5a, 0x89, 0x43, 0xfc,
	0x18, 0x74, 0xca, 0x2e, 0x22, 0xa8, 0xa0, 0xf6, 0xa6, 0x09, 0x4c, 0x00, 0x28, 0xbb, 0x88, 0xd1,
	0xa2, 0xda, 0x4e, 0x65, 0x24, 0x6d, 0x0e, 0x87, 0x11, 0xad, 0x85, 0x74, 0x92, 0x90, 0xb4, 0x39,
	0x1c, 0xc6, 0x74, 0x29, 0xa4, 0xa7, 0x19, 0xbc, 0x03, 0xfa, 0x40, 0x55, 0x1e, 0x32, 0xb7, 0xbe,
	0xdc, 0x28, 0x34, 0x97, 0xb7, 0x9e, 0x4c, 0x9f, 0x34, 0xbe, 0xd4, 0xa6, 0x15, 0xd7, 0xb4, 0x6d,
	0xe1, 0x4d, 0xe8, 0x94, 0xc1, 0xbb, 0x00, 0x4e, 0xa8, 0x25, 0x15, 0x56, 0x94, 0x82, 0xb1, 0x40,
	0xe1, 0x38, 0x29, 0x0a, 0x25, 0x52, 0x14, 0x3e, 0x80, 0x15, 0x2f, 0xbe, 0xaf, 0x54, 0xa9, 0x28,
	0x95, 0xa7, 0x0b, 0x54, 0x68, 0xaa, 0x2c, 0xd4, 0x99, 0x21, 0xf1, 0x07, 0xa8, 0x78, 0xc9, 0xd3,
	0x48, 0xa9, 0xaa, 0x92, 0x7a, 0xb6, 0x58, 0xea, 0xae, 0xa7, 0x59, 0x56, 0xda, 0x62, 0xf1, 0x43,
	0x4a, 0xad, 0xd5, 0x7b, 0x6d, 0x99, 0xa9, 0xb2, 0xc8, 0x56, 0x9a, 0x94, 0xb6, 0x58, 0xf2, 0xe6,
	0x52, 0xaa, 0x76, 0xaf, 0x2d, 0x33, 0x5d, 0x17, 0xd9, 0x9a, 0x61, 0xa5, 0x2d, 0xc1, 0x46, 0x2e,
	0xf7, 0x06, 0x76, 0x5f, 0x6a, 0xad, 0xdd, 0x6b, 0xab, 0x97, 0x2a, 0x8b, 0x6c, 0xa5, 0xc9, 0x8d,
	0x6d, 0xa8, 0xce, 0xda, 0xc6, 0x35, 0x28, 0x7c, 0xe5, 0x13, 0xf5, 0xcd, 0xd5, 0xa8, 0x5c, 0x2e,
	0xfe, 0xfd, 0xbc, 0xcd, 0xbf, 0x46, 0x1b, 0xef, 0x60, 0xf5, 0x8e, 0xd3, 0x4c, 0xf8, 0x0e, 0xac,
	0xcd, 0x75, 0x33, 0x93, 0xc0, 0x7b, 0xc0, 0xf3, 0x3d, 0xcc, 0x6a, 0x61, 0xae, 0x73, 0x59, 0x2d,
	0xcc, 0xf7, 0x2b, 0xab, 0x85, 0xb9, 0x2e, 0x65, 0x11, 0x30, 0xde, 0x40, 0xa5, 0xe5, 0x8c, 0x6d,
	0x31, 0xb0, 0xfb, 0xe6, 0x67, 0xe1, 0x78, 0x72, 0xce, 0x98, 0xa7, 0xa7, 0x1e, 0xf7, 0xc3, 0x01,
	0xa4, 0xd3, 0x38, 0x8c, 0x86, 0x5e, 0x5e, 0x25, 0xe5, 0xd0, 0xfb, 0x08, 0x2b, 0x2d, 0x36, 0xe2,
	0x1e, 0x6b, 0x39, 0xf6, 0xd9, 0xa0, 0x2f, 0x8f, 0x3d, 0xf1, 0x86, 0x11, 0x25, 0x97, 0x78, 0x03,
	0xca, 0x07, 0x8e, 0x2f, 0x6c, 0x36, 0xe2, 0x11, 0x97, 0xc4, 0x18, 0x43, 0xb1, 0xe3, 0x78, 0x42,
	0x0d, 0x2c, 0x9d, 0xaa, 0xb5, 0x3a, 0xa1, 0xa3, 0x66, 0x94, 0x3c, 0xa1, 0x63, 0x2c, 0x81, 0xd6,
	0x15, 0xcc, 0x13, 0x46, 0x09, 0x8a, 0x5d, 0xe1, 0xb8, 0x86, 0x0e, 0x4b, 0x94, 0xfb, 0x2a, 0xb5,
	0x0a, 0x95, 0xae, 0x60, 0x62, 0xec, 0x53, 0xfe, 0x6d, 0xcc, 0x7d, 0x61, 0x3c, 0x87, 0x6a, 0x9c,
	0xf0, 0x5d, 0xc7, 0xf6, 0xd5, 0xec, 0xf6, 0x05, 0x13, 0x3c, 0xb2, 0x14, 0x06, 0xc6, 0x3a, 0x60,
	0xcb, 0x3e, 0x73, 0xd4, 0xad, 0xb9, 0x17, 0xd3, 0xfb, 0xf0, 0x60, 0x26, 0x1b, 0x49, 0x64, 0x9e,
	0xc6, 0xbb, 0xaf, 0x2e, 0xaf, 0x49, 0xee, 0xea, 0x9a, 0xe4, 0x6e, 0xaf, 0x09, 0xfa, 0x1e, 0x10,
	0xf4, 0x2b, 0x20, 0xe8, 0x77, 0x40, 0xd0, 0x65, 0x40, 0xd0, 0x9f, 0x80, 0xa0, 0xbf, 0x01, 0xc9,
	0xdd, 0x06, 0x04, 0xfd, 0xb8, 0x21, 0xb9, 0xcb, 0x1b, 0x92, 0xbb, 0xba, 0x21, 0xb9, 0x4f, 0x25,
	0xf5, 0x87, 0xf5, 0xf2, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0x63, 0x31, 0xc7, 0xc2, 0x06,
	0x00, 0x00,
}

func (x Event_EventType) String() string {
	s, ok := Event_EventType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *Event) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Event)
	if !ok {
		that2, ok := that.(Event)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	if this.ID != that1.ID {
		return false
	}
	return true
}
func (this *Snapshot) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Snapshot)
	if !ok {
		that2, ok := that.(Snapshot)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Inputs != that1.Inputs {
		return false
	}
	if this.Outputs != that1.Outputs {
		return false
	}
	if this.RawInputs != that1.RawInputs {
		return false
	}
	if this.RawOutputs != that1.RawOutputs {
		return false
	}
	if this.AllInputs != that1.AllInputs {
		return false
	}
	if this.AllOutputs != that1.AllOutputs {
		return false
	}
	if len(this.InputsMap) != len(that1.InputsMap) {
		return false
	}
	for i := range this.InputsMap {
		if this.InputsMap[i] != that1.InputsMap[i] {
			return false
		}
	}
	if len(this.OutputsMap) != len(that1.OutputsMap) {
		return false
	}
	for i := range this.OutputsMap {
		if this.OutputsMap[i] != that1.OutputsMap[i] {
			return false
		}
	}
	if len(this.RawInputsMap) != len(that1.RawInputsMap) {
		return false
	}
	for i := range this.RawInputsMap {
		if this.RawInputsMap[i] != that1.RawInputsMap[i] {
			return false
		}
	}
	if len(this.RawOutputsMap) != len(that1.RawOutputsMap) {
		return false
	}
	for i := range this.RawOutputsMap {
		if this.RawOutputsMap[i] != that1.RawOutputsMap[i] {
			return false
		}
	}
	if len(this.AllInputsMap) != len(that1.AllInputsMap) {
		return false
	}
	for i := range this.AllInputsMap {
		if this.AllInputsMap[i] != that1.AllInputsMap[i] {
			return false
		}
	}
	if len(this.AllOutputsMap) != len(that1.AllOutputsMap) {
		return false
	}
	for i := range this.AllOutputsMap {
		if this.AllOutputsMap[i] != that1.AllOutputsMap[i] {
			return false
		}
	}
	if len(this.TamperingMap) != len(that1.TamperingMap) {
		return false
	}
	for i := range this.TamperingMap {
		if this.TamperingMap[i] != that1.TamperingMap[i] {
			return false
		}
	}
	return true
}
func (this *CountingActor) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CountingActor)
	if !ok {
		that2, ok := that.(CountingActor)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Address != that1.Address {
		return false
	}
	if this.ID != that1.ID {
		return false
	}
	return true
}
func (this *CameraConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CameraConfig)
	if !ok {
		that2, ok := that.(CameraConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Url != that1.Url {
		return false
	}
	if this.Hostname != that1.Hostname {
		return false
	}
	if this.Port != that1.Port {
		return false
	}
	if this.IP != that1.IP {
		return false
	}
	return true
}
func (this *Start) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Start)
	if !ok {
		that2, ok := that.(Start)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *Stop) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Stop)
	if !ok {
		that2, ok := that.(Stop)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *Restart) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Restart)
	if !ok {
		that2, ok := that.(Restart)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *StatusRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StatusRequest)
	if !ok {
		that2, ok := that.(StatusRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *StatusResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StatusResponse)
	if !ok {
		that2, ok := that.(StatusResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.State != that1.State {
		return false
	}
	return true
}
func (this *InfoCounterRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*InfoCounterRequest)
	if !ok {
		that2, ok := that.(InfoCounterRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *InfoCounterResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*InfoCounterResponse)
	if !ok {
		that2, ok := that.(InfoCounterResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Inputs != that1.Inputs {
		return false
	}
	if this.Outputs != that1.Outputs {
		return false
	}
	return true
}
func (this *Event) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&messages.Event{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Value: "+fmt.Sprintf("%#v", this.Value)+",\n")
	s = append(s, "ID: "+fmt.Sprintf("%#v", this.ID)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Snapshot) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 17)
	s = append(s, "&messages.Snapshot{")
	s = append(s, "Inputs: "+fmt.Sprintf("%#v", this.Inputs)+",\n")
	s = append(s, "Outputs: "+fmt.Sprintf("%#v", this.Outputs)+",\n")
	s = append(s, "RawInputs: "+fmt.Sprintf("%#v", this.RawInputs)+",\n")
	s = append(s, "RawOutputs: "+fmt.Sprintf("%#v", this.RawOutputs)+",\n")
	s = append(s, "AllInputs: "+fmt.Sprintf("%#v", this.AllInputs)+",\n")
	s = append(s, "AllOutputs: "+fmt.Sprintf("%#v", this.AllOutputs)+",\n")
	keysForInputsMap := make([]int32, 0, len(this.InputsMap))
	for k, _ := range this.InputsMap {
		keysForInputsMap = append(keysForInputsMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForInputsMap)
	mapStringForInputsMap := "map[int32]int64{"
	for _, k := range keysForInputsMap {
		mapStringForInputsMap += fmt.Sprintf("%#v: %#v,", k, this.InputsMap[k])
	}
	mapStringForInputsMap += "}"
	if this.InputsMap != nil {
		s = append(s, "InputsMap: "+mapStringForInputsMap+",\n")
	}
	keysForOutputsMap := make([]int32, 0, len(this.OutputsMap))
	for k, _ := range this.OutputsMap {
		keysForOutputsMap = append(keysForOutputsMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForOutputsMap)
	mapStringForOutputsMap := "map[int32]int64{"
	for _, k := range keysForOutputsMap {
		mapStringForOutputsMap += fmt.Sprintf("%#v: %#v,", k, this.OutputsMap[k])
	}
	mapStringForOutputsMap += "}"
	if this.OutputsMap != nil {
		s = append(s, "OutputsMap: "+mapStringForOutputsMap+",\n")
	}
	keysForRawInputsMap := make([]int32, 0, len(this.RawInputsMap))
	for k, _ := range this.RawInputsMap {
		keysForRawInputsMap = append(keysForRawInputsMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForRawInputsMap)
	mapStringForRawInputsMap := "map[int32]int64{"
	for _, k := range keysForRawInputsMap {
		mapStringForRawInputsMap += fmt.Sprintf("%#v: %#v,", k, this.RawInputsMap[k])
	}
	mapStringForRawInputsMap += "}"
	if this.RawInputsMap != nil {
		s = append(s, "RawInputsMap: "+mapStringForRawInputsMap+",\n")
	}
	keysForRawOutputsMap := make([]int32, 0, len(this.RawOutputsMap))
	for k, _ := range this.RawOutputsMap {
		keysForRawOutputsMap = append(keysForRawOutputsMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForRawOutputsMap)
	mapStringForRawOutputsMap := "map[int32]int64{"
	for _, k := range keysForRawOutputsMap {
		mapStringForRawOutputsMap += fmt.Sprintf("%#v: %#v,", k, this.RawOutputsMap[k])
	}
	mapStringForRawOutputsMap += "}"
	if this.RawOutputsMap != nil {
		s = append(s, "RawOutputsMap: "+mapStringForRawOutputsMap+",\n")
	}
	keysForAllInputsMap := make([]int32, 0, len(this.AllInputsMap))
	for k, _ := range this.AllInputsMap {
		keysForAllInputsMap = append(keysForAllInputsMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForAllInputsMap)
	mapStringForAllInputsMap := "map[int32]int64{"
	for _, k := range keysForAllInputsMap {
		mapStringForAllInputsMap += fmt.Sprintf("%#v: %#v,", k, this.AllInputsMap[k])
	}
	mapStringForAllInputsMap += "}"
	if this.AllInputsMap != nil {
		s = append(s, "AllInputsMap: "+mapStringForAllInputsMap+",\n")
	}
	keysForAllOutputsMap := make([]int32, 0, len(this.AllOutputsMap))
	for k, _ := range this.AllOutputsMap {
		keysForAllOutputsMap = append(keysForAllOutputsMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForAllOutputsMap)
	mapStringForAllOutputsMap := "map[int32]int64{"
	for _, k := range keysForAllOutputsMap {
		mapStringForAllOutputsMap += fmt.Sprintf("%#v: %#v,", k, this.AllOutputsMap[k])
	}
	mapStringForAllOutputsMap += "}"
	if this.AllOutputsMap != nil {
		s = append(s, "AllOutputsMap: "+mapStringForAllOutputsMap+",\n")
	}
	keysForTamperingMap := make([]int32, 0, len(this.TamperingMap))
	for k, _ := range this.TamperingMap {
		keysForTamperingMap = append(keysForTamperingMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForTamperingMap)
	mapStringForTamperingMap := "map[int32]int64{"
	for _, k := range keysForTamperingMap {
		mapStringForTamperingMap += fmt.Sprintf("%#v: %#v,", k, this.TamperingMap[k])
	}
	mapStringForTamperingMap += "}"
	if this.TamperingMap != nil {
		s = append(s, "TamperingMap: "+mapStringForTamperingMap+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CountingActor) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&messages.CountingActor{")
	s = append(s, "Address: "+fmt.Sprintf("%#v", this.Address)+",\n")
	s = append(s, "ID: "+fmt.Sprintf("%#v", this.ID)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CameraConfig) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&messages.CameraConfig{")
	s = append(s, "Url: "+fmt.Sprintf("%#v", this.Url)+",\n")
	s = append(s, "Hostname: "+fmt.Sprintf("%#v", this.Hostname)+",\n")
	s = append(s, "Port: "+fmt.Sprintf("%#v", this.Port)+",\n")
	s = append(s, "IP: "+fmt.Sprintf("%#v", this.IP)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Start) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&messages.Start{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Stop) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&messages.Stop{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Restart) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&messages.Restart{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *StatusRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&messages.StatusRequest{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *StatusResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&messages.StatusResponse{")
	s = append(s, "State: "+fmt.Sprintf("%#v", this.State)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *InfoCounterRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&messages.InfoCounterRequest{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *InfoCounterResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&messages.InfoCounterResponse{")
	s = append(s, "Inputs: "+fmt.Sprintf("%#v", this.Inputs)+",\n")
	s = append(s, "Outputs: "+fmt.Sprintf("%#v", this.Outputs)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringMessages(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Event) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Event) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Event) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ID != 0 {
		i = encodeVarintMessages(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x18
	}
	if m.Value != 0 {
		i = encodeVarintMessages(dAtA, i, uint64(m.Value))
		i--
		dAtA[i] = 0x10
	}
	if m.Type != 0 {
		i = encodeVarintMessages(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Snapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Snapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Snapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TamperingMap) > 0 {
		for k := range m.TamperingMap {
			v := m.TamperingMap[k]
			baseI := i
			i = encodeVarintMessages(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i = encodeVarintMessages(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintMessages(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x8a
		}
	}
	if len(m.AllOutputsMap) > 0 {
		for k := range m.AllOutputsMap {
			v := m.AllOutputsMap[k]
			baseI := i
			i = encodeVarintMessages(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i = encodeVarintMessages(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintMessages(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
	}
	if len(m.AllInputsMap) > 0 {
		for k := range m.AllInputsMap {
			v := m.AllInputsMap[k]
			baseI := i
			i = encodeVarintMessages(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i = encodeVarintMessages(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintMessages(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x7a
		}
	}
	if len(m.RawOutputsMap) > 0 {
		for k := range m.RawOutputsMap {
			v := m.RawOutputsMap[k]
			baseI := i
			i = encodeVarintMessages(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i = encodeVarintMessages(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintMessages(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x72
		}
	}
	if len(m.RawInputsMap) > 0 {
		for k := range m.RawInputsMap {
			v := m.RawInputsMap[k]
			baseI := i
			i = encodeVarintMessages(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i = encodeVarintMessages(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintMessages(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.OutputsMap) > 0 {
		for k := range m.OutputsMap {
			v := m.OutputsMap[k]
			baseI := i
			i = encodeVarintMessages(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i = encodeVarintMessages(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintMessages(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.InputsMap) > 0 {
		for k := range m.InputsMap {
			v := m.InputsMap[k]
			baseI := i
			i = encodeVarintMessages(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i = encodeVarintMessages(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintMessages(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x5a
		}
	}
	if m.AllOutputs != 0 {
		i = encodeVarintMessages(dAtA, i, uint64(m.AllOutputs))
		i--
		dAtA[i] = 0x30
	}
	if m.AllInputs != 0 {
		i = encodeVarintMessages(dAtA, i, uint64(m.AllInputs))
		i--
		dAtA[i] = 0x28
	}
	if m.RawOutputs != 0 {
		i = encodeVarintMessages(dAtA, i, uint64(m.RawOutputs))
		i--
		dAtA[i] = 0x20
	}
	if m.RawInputs != 0 {
		i = encodeVarintMessages(dAtA, i, uint64(m.RawInputs))
		i--
		dAtA[i] = 0x18
	}
	if m.Outputs != 0 {
		i = encodeVarintMessages(dAtA, i, uint64(m.Outputs))
		i--
		dAtA[i] = 0x10
	}
	if m.Inputs != 0 {
		i = encodeVarintMessages(dAtA, i, uint64(m.Inputs))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CountingActor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CountingActor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CountingActor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintMessages(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintMessages(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CameraConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CameraConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CameraConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IP) > 0 {
		i -= len(m.IP)
		copy(dAtA[i:], m.IP)
		i = encodeVarintMessages(dAtA, i, uint64(len(m.IP)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Port) > 0 {
		i -= len(m.Port)
		copy(dAtA[i:], m.Port)
		i = encodeVarintMessages(dAtA, i, uint64(len(m.Port)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Hostname) > 0 {
		i -= len(m.Hostname)
		copy(dAtA[i:], m.Hostname)
		i = encodeVarintMessages(dAtA, i, uint64(len(m.Hostname)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintMessages(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Start) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Start) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Start) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Stop) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Stop) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Stop) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Restart) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Restart) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Restart) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *StatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *StatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintMessages(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InfoCounterRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InfoCounterRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InfoCounterRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *InfoCounterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InfoCounterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InfoCounterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Outputs != 0 {
		i = encodeVarintMessages(dAtA, i, uint64(m.Outputs))
		i--
		dAtA[i] = 0x10
	}
	if m.Inputs != 0 {
		i = encodeVarintMessages(dAtA, i, uint64(m.Inputs))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMessages(dAtA []byte, offset int, v uint64) int {
	offset -= sovMessages(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Event) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovMessages(uint64(m.Type))
	}
	if m.Value != 0 {
		n += 1 + sovMessages(uint64(m.Value))
	}
	if m.ID != 0 {
		n += 1 + sovMessages(uint64(m.ID))
	}
	return n
}

func (m *Snapshot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Inputs != 0 {
		n += 1 + sovMessages(uint64(m.Inputs))
	}
	if m.Outputs != 0 {
		n += 1 + sovMessages(uint64(m.Outputs))
	}
	if m.RawInputs != 0 {
		n += 1 + sovMessages(uint64(m.RawInputs))
	}
	if m.RawOutputs != 0 {
		n += 1 + sovMessages(uint64(m.RawOutputs))
	}
	if m.AllInputs != 0 {
		n += 1 + sovMessages(uint64(m.AllInputs))
	}
	if m.AllOutputs != 0 {
		n += 1 + sovMessages(uint64(m.AllOutputs))
	}
	if len(m.InputsMap) > 0 {
		for k, v := range m.InputsMap {
			_ = k
			_ = v
			mapEntrySize := 1 + sovMessages(uint64(k)) + 1 + sovMessages(uint64(v))
			n += mapEntrySize + 1 + sovMessages(uint64(mapEntrySize))
		}
	}
	if len(m.OutputsMap) > 0 {
		for k, v := range m.OutputsMap {
			_ = k
			_ = v
			mapEntrySize := 1 + sovMessages(uint64(k)) + 1 + sovMessages(uint64(v))
			n += mapEntrySize + 1 + sovMessages(uint64(mapEntrySize))
		}
	}
	if len(m.RawInputsMap) > 0 {
		for k, v := range m.RawInputsMap {
			_ = k
			_ = v
			mapEntrySize := 1 + sovMessages(uint64(k)) + 1 + sovMessages(uint64(v))
			n += mapEntrySize + 1 + sovMessages(uint64(mapEntrySize))
		}
	}
	if len(m.RawOutputsMap) > 0 {
		for k, v := range m.RawOutputsMap {
			_ = k
			_ = v
			mapEntrySize := 1 + sovMessages(uint64(k)) + 1 + sovMessages(uint64(v))
			n += mapEntrySize + 1 + sovMessages(uint64(mapEntrySize))
		}
	}
	if len(m.AllInputsMap) > 0 {
		for k, v := range m.AllInputsMap {
			_ = k
			_ = v
			mapEntrySize := 1 + sovMessages(uint64(k)) + 1 + sovMessages(uint64(v))
			n += mapEntrySize + 1 + sovMessages(uint64(mapEntrySize))
		}
	}
	if len(m.AllOutputsMap) > 0 {
		for k, v := range m.AllOutputsMap {
			_ = k
			_ = v
			mapEntrySize := 1 + sovMessages(uint64(k)) + 1 + sovMessages(uint64(v))
			n += mapEntrySize + 2 + sovMessages(uint64(mapEntrySize))
		}
	}
	if len(m.TamperingMap) > 0 {
		for k, v := range m.TamperingMap {
			_ = k
			_ = v
			mapEntrySize := 1 + sovMessages(uint64(k)) + 1 + sovMessages(uint64(v))
			n += mapEntrySize + 2 + sovMessages(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *CountingActor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovMessages(uint64(l))
	}
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovMessages(uint64(l))
	}
	return n
}

func (m *CameraConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovMessages(uint64(l))
	}
	l = len(m.Hostname)
	if l > 0 {
		n += 1 + l + sovMessages(uint64(l))
	}
	l = len(m.Port)
	if l > 0 {
		n += 1 + l + sovMessages(uint64(l))
	}
	l = len(m.IP)
	if l > 0 {
		n += 1 + l + sovMessages(uint64(l))
	}
	return n
}

func (m *Start) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Stop) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Restart) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *StatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *StatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovMessages(uint64(l))
	}
	return n
}

func (m *InfoCounterRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *InfoCounterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Inputs != 0 {
		n += 1 + sovMessages(uint64(m.Inputs))
	}
	if m.Outputs != 0 {
		n += 1 + sovMessages(uint64(m.Outputs))
	}
	return n
}

func sovMessages(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMessages(x uint64) (n int) {
	return sovMessages(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Event) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Event{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Value:` + fmt.Sprintf("%v", this.Value) + `,`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Snapshot) String() string {
	if this == nil {
		return "nil"
	}
	keysForInputsMap := make([]int32, 0, len(this.InputsMap))
	for k, _ := range this.InputsMap {
		keysForInputsMap = append(keysForInputsMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForInputsMap)
	mapStringForInputsMap := "map[int32]int64{"
	for _, k := range keysForInputsMap {
		mapStringForInputsMap += fmt.Sprintf("%v: %v,", k, this.InputsMap[k])
	}
	mapStringForInputsMap += "}"
	keysForOutputsMap := make([]int32, 0, len(this.OutputsMap))
	for k, _ := range this.OutputsMap {
		keysForOutputsMap = append(keysForOutputsMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForOutputsMap)
	mapStringForOutputsMap := "map[int32]int64{"
	for _, k := range keysForOutputsMap {
		mapStringForOutputsMap += fmt.Sprintf("%v: %v,", k, this.OutputsMap[k])
	}
	mapStringForOutputsMap += "}"
	keysForRawInputsMap := make([]int32, 0, len(this.RawInputsMap))
	for k, _ := range this.RawInputsMap {
		keysForRawInputsMap = append(keysForRawInputsMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForRawInputsMap)
	mapStringForRawInputsMap := "map[int32]int64{"
	for _, k := range keysForRawInputsMap {
		mapStringForRawInputsMap += fmt.Sprintf("%v: %v,", k, this.RawInputsMap[k])
	}
	mapStringForRawInputsMap += "}"
	keysForRawOutputsMap := make([]int32, 0, len(this.RawOutputsMap))
	for k, _ := range this.RawOutputsMap {
		keysForRawOutputsMap = append(keysForRawOutputsMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForRawOutputsMap)
	mapStringForRawOutputsMap := "map[int32]int64{"
	for _, k := range keysForRawOutputsMap {
		mapStringForRawOutputsMap += fmt.Sprintf("%v: %v,", k, this.RawOutputsMap[k])
	}
	mapStringForRawOutputsMap += "}"
	keysForAllInputsMap := make([]int32, 0, len(this.AllInputsMap))
	for k, _ := range this.AllInputsMap {
		keysForAllInputsMap = append(keysForAllInputsMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForAllInputsMap)
	mapStringForAllInputsMap := "map[int32]int64{"
	for _, k := range keysForAllInputsMap {
		mapStringForAllInputsMap += fmt.Sprintf("%v: %v,", k, this.AllInputsMap[k])
	}
	mapStringForAllInputsMap += "}"
	keysForAllOutputsMap := make([]int32, 0, len(this.AllOutputsMap))
	for k, _ := range this.AllOutputsMap {
		keysForAllOutputsMap = append(keysForAllOutputsMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForAllOutputsMap)
	mapStringForAllOutputsMap := "map[int32]int64{"
	for _, k := range keysForAllOutputsMap {
		mapStringForAllOutputsMap += fmt.Sprintf("%v: %v,", k, this.AllOutputsMap[k])
	}
	mapStringForAllOutputsMap += "}"
	keysForTamperingMap := make([]int32, 0, len(this.TamperingMap))
	for k, _ := range this.TamperingMap {
		keysForTamperingMap = append(keysForTamperingMap, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForTamperingMap)
	mapStringForTamperingMap := "map[int32]int64{"
	for _, k := range keysForTamperingMap {
		mapStringForTamperingMap += fmt.Sprintf("%v: %v,", k, this.TamperingMap[k])
	}
	mapStringForTamperingMap += "}"
	s := strings.Join([]string{`&Snapshot{`,
		`Inputs:` + fmt.Sprintf("%v", this.Inputs) + `,`,
		`Outputs:` + fmt.Sprintf("%v", this.Outputs) + `,`,
		`RawInputs:` + fmt.Sprintf("%v", this.RawInputs) + `,`,
		`RawOutputs:` + fmt.Sprintf("%v", this.RawOutputs) + `,`,
		`AllInputs:` + fmt.Sprintf("%v", this.AllInputs) + `,`,
		`AllOutputs:` + fmt.Sprintf("%v", this.AllOutputs) + `,`,
		`InputsMap:` + mapStringForInputsMap + `,`,
		`OutputsMap:` + mapStringForOutputsMap + `,`,
		`RawInputsMap:` + mapStringForRawInputsMap + `,`,
		`RawOutputsMap:` + mapStringForRawOutputsMap + `,`,
		`AllInputsMap:` + mapStringForAllInputsMap + `,`,
		`AllOutputsMap:` + mapStringForAllOutputsMap + `,`,
		`TamperingMap:` + mapStringForTamperingMap + `,`,
		`}`,
	}, "")
	return s
}
func (this *CountingActor) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CountingActor{`,
		`Address:` + fmt.Sprintf("%v", this.Address) + `,`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CameraConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CameraConfig{`,
		`Url:` + fmt.Sprintf("%v", this.Url) + `,`,
		`Hostname:` + fmt.Sprintf("%v", this.Hostname) + `,`,
		`Port:` + fmt.Sprintf("%v", this.Port) + `,`,
		`IP:` + fmt.Sprintf("%v", this.IP) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Start) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Start{`,
		`}`,
	}, "")
	return s
}
func (this *Stop) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Stop{`,
		`}`,
	}, "")
	return s
}
func (this *Restart) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Restart{`,
		`}`,
	}, "")
	return s
}
func (this *StatusRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StatusRequest{`,
		`}`,
	}, "")
	return s
}
func (this *StatusResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StatusResponse{`,
		`State:` + fmt.Sprintf("%v", this.State) + `,`,
		`}`,
	}, "")
	return s
}
func (this *InfoCounterRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&InfoCounterRequest{`,
		`}`,
	}, "")
	return s
}
func (this *InfoCounterResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&InfoCounterResponse{`,
		`Inputs:` + fmt.Sprintf("%v", this.Inputs) + `,`,
		`Outputs:` + fmt.Sprintf("%v", this.Outputs) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringMessages(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Event) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Event: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Event: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= Event_EventType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			m.Value = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Value |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Snapshot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Snapshot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Snapshot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inputs", wireType)
			}
			m.Inputs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Inputs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outputs", wireType)
			}
			m.Outputs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Outputs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawInputs", wireType)
			}
			m.RawInputs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RawInputs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawOutputs", wireType)
			}
			m.RawOutputs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RawOutputs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllInputs", wireType)
			}
			m.AllInputs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AllInputs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllOutputs", wireType)
			}
			m.AllOutputs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AllOutputs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InputsMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.InputsMap == nil {
				m.InputsMap = make(map[int32]int64)
			}
			var mapkey int32
			var mapvalue int64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMessages
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMessages
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMessages
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipMessages(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthMessages
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.InputsMap[mapkey] = mapvalue
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputsMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OutputsMap == nil {
				m.OutputsMap = make(map[int32]int64)
			}
			var mapkey int32
			var mapvalue int64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMessages
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMessages
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMessages
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipMessages(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthMessages
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.OutputsMap[mapkey] = mapvalue
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawInputsMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RawInputsMap == nil {
				m.RawInputsMap = make(map[int32]int64)
			}
			var mapkey int32
			var mapvalue int64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMessages
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMessages
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMessages
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipMessages(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthMessages
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.RawInputsMap[mapkey] = mapvalue
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawOutputsMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RawOutputsMap == nil {
				m.RawOutputsMap = make(map[int32]int64)
			}
			var mapkey int32
			var mapvalue int64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMessages
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMessages
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMessages
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipMessages(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthMessages
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.RawOutputsMap[mapkey] = mapvalue
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllInputsMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AllInputsMap == nil {
				m.AllInputsMap = make(map[int32]int64)
			}
			var mapkey int32
			var mapvalue int64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMessages
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMessages
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMessages
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipMessages(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthMessages
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.AllInputsMap[mapkey] = mapvalue
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllOutputsMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AllOutputsMap == nil {
				m.AllOutputsMap = make(map[int32]int64)
			}
			var mapkey int32
			var mapvalue int64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMessages
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMessages
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMessages
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipMessages(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthMessages
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.AllOutputsMap[mapkey] = mapvalue
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TamperingMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TamperingMap == nil {
				m.TamperingMap = make(map[int32]int64)
			}
			var mapkey int32
			var mapvalue int64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMessages
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMessages
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMessages
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipMessages(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthMessages
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.TamperingMap[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CountingActor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CountingActor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CountingActor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CameraConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CameraConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CameraConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hostname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hostname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Port = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IP", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IP = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Start) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Start: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Start: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Stop) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Stop: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Stop: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Restart) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Restart: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Restart: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InfoCounterRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InfoCounterRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InfoCounterRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InfoCounterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InfoCounterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InfoCounterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inputs", wireType)
			}
			m.Inputs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Inputs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outputs", wireType)
			}
			m.Outputs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Outputs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessages(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMessages
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMessages
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMessages
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMessages        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessages          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMessages = fmt.Errorf("proto: unexpected end of group")
)
